name: Android Test Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Android SDK and emulator
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Android/sdk
          ~/.android
        key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-android-sdk-

    - name: Setup Android SDK
      run: /Users/runner/work/remote_assistance_ci_cd_demo/remote_assistance_ci_cd_demo/set_up_android_sdk.sh

    - name: Create and start emulator
      run: /Users/runner/work/remote_assistance_ci_cd_demo/remote_assistance_ci_cd_demo/start_emulator.sh

    - name: Check disk space
      run: df -h

    - name: Build with gradle
      run: ./gradlew build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: testBuild.apk
        path: app/build/output/apk/debug/app-debug.apk


#    - name: Katalon Studio Github Action
#      uses: katalon-studio/katalon-studio-github-action@v3.0
#      with:
#        version: '7.5.5'
#        projectPath: '/katalon-tests'
#        args: '-noSplash -runMode=console -projectPath="/home/runner/work/remote_assistance_ci_cd_demo/remote_assistance_ci_cd_demo/katalon-tests/Test.prj" -retry=0 -testSuitePath="/home/runner/work/remote_assistance_ci_cd_demo/remote_assistance_ci_cd_demo/katalon-tests/Test Suites/Remote Assistance Demo Test" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="85c71a78-37fe-491c-8054-e9409964c277" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'

  


        
