name: Android Test Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Katalon Studio
      uses: actions/cache@v2
      with:
        path: ~/katalon
        key: ${{ runner.os }}-katalon-${{ hashFiles('**/projectPath') }}
        restore-keys: |
          ${{ runner.os }}-katalon-

    - name: Download and Install Katalon Studio
      run: |
        KATALON_VERSION=8.x.x
        wget -O katalon-studio.deb "https://github.com/katalon-studio/katalon-studio/releases/download/v$KATALON_VERSION/Katalon_Studio_Engine_Linux_64-$KATALON_VERSION.deb"
        sudo dpkg -i katalon-studio.deb
        #katalonc -noSplash -runMode=console -projectPath="$(pwd)/your-project-folder" -retry=0 -testSuitePath="Test Suites/your_test_suite" -executionProfile="default" -browserType="Android" -apiKey="your_Katalon_API_key"
        ./katalonc -noSplash -runMode=console -projectPath="/katalon-tests/Test.prj" -retry=0 -testSuitePath="/katalon-tests/Test Suites/Remote Assistance Demo Test" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="85c71a78-37fe-491c-8054-e9409964c277" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true -appiumDirectory="/opt/homebrew/lib/node_modules/appium"
    - name: Upload Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: path/to/your/report/folder


        
